version: '3.5'
services:
 database:
                image: mysql
                cap_add:
                        - SYS_NICE  # CAP_SYS_NICE
                container_name: mysqlDatabase
                hostname: mysql-database
                networks:
                        service-discovery-network:
                                aliases:
                                        - database
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: dumbAPIdatabase
                volumes:
                        - mysqldatabase:/var/lib/mysql
 dumbAPI:
                build: .
                image: dumbapiimage
                container_name: dumbAPIcontainer
                environment:
                        DATABASE_PASSWORD: password
                        DATABASE_DOMAIN: database
                        DATABASE_SCHEME: dumbapi
                ports: 
                        - "8081:8081"
                networks:
                        service-discovery-network:
                                 aliases:
                                         - dumbapi
                volumes:
                        - $HOME/.m2:/root/.m2
                depends_on:
                        - database
networks:
        service-discovery-network:
                name: service-discovery-network
                driver: bridge

volumes:
        mysqldatabase:
